    pipeline {
        agent any
        tools {
            maven 'maven-3.6.2'
        }
        stages {
            stage('Build do projeto e da imagem') {
                steps {
                    script{
                        tag = env.GIT_BRANCH
                        appEnv = tag.equals("dev")  ? "dev" : "prod"
                        jobBuild = "udiapub-jobs-deploy-${appEnv}"

                        sh "mvn clean install -P ${appEnv}"
                        appName = "udiapub-job-image"
                        registryHost = "127.0.0.1:30400/"
                        imageName = "${registryHost}${appName}:${tag}"
                        customImage = docker.build("${imageName}", "./adapter/job")
                    }
                }
            }
            stage('Testando a imagem') {
                steps {
                    script{
                         sh '''#!/bin/sh

                                echo "verificar e remover container de teste em execução"
                                HAS_CONTAINER=$(docker ps -a -aq --filter name=udiapub-job_teste)
                                if [ ${#HAS_CONTAINER} -ge 2 ]; then
                                  docker rm -f $HAS_CONTAINER
                                fi


                                echo "executar a imagem do container"
                                docker run -d --name udiapub-job_teste udiapub-job-image-build


                                echo "esperando a aplicação subir por 25 seg"
                                NEXT_WAIT_TIME=0
                                APP_STATUS=
                                until [ $NEXT_WAIT_TIME -gt 5 ] || [ ${#APP_STATUS} -gt 0  ]; do
                                  sleep 5;
                                  APP_STATUS=$(docker logs udiapub-job_teste | grep "Started UdiaPubJobApplication")
                                  NEXT_WAIT_TIME=$(( $NEXT_WAIT_TIME + 1 ));
                                done


                                echo "derrubando o container após utiliza-lo no teste"
                                docker rm -f udiapub-job_teste


                                echo "verificar se no log contem o texto \'Started UdiaPubJobApplication\' para considerar que subiu com sucesso"
                                if [ ${#APP_STATUS} -eq 0 ]; then
                                  exit 1
                                fi'''

                        customImage.push()
                    }
                }
            }
            stage (deploy) {
                steps {
                    script {
                        build job: "${jobBuild}", wait: false, parameters: [[$class: 'StringParameterValue', name: 'image', value: "${imageName}"]]
                    }
                }
            }
        }
    }